//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class google_map
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        public string Address { get; set; }
        public double Lat { get; set; }
        public Nullable<double> Long { get; set; }
    }
}
